- name: Download K3S kubeconfig to localhost
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ k3s_download_kubeconf_path }}/{{ k3s_download_kubeconf_file_name }}"
    # dest: /root/.kube/config
    flat: yes
  when:
  - inventory_hostname == groups["k3s_cluster"].0

- name: Replace loopback IP by master server API IP
  ansible.builtin.replace:
    path: "{{ k3s_download_kubeconf_path }}/{{ k3s_download_kubeconf_file_name }}"
    mode: '0600'
    regexp: '127.0.0.1'
    replace: "{{ k3s_api_ip }}"
  delegate_to: localhost
  become: false
  when:
  - inventory_hostname == groups["k3s_cluster"].0
